const entities = {
  OPERATION_RESPONSE: 'OPERATION_RESPONSE',
  CLOSE_PRINT_WINDOW: 'CLOSE_PRINT_WINDOW',
  OPEN_PRINT_WINDOW: 'OPEN_PRINT_WINDOW',
  OPERATION_REQUEST: 'OPERATION_REQUEST',
  OPEN_URL: 'OPEN_URL',
  PROVIDER: 'PROVIDER',
  CUSTOMER: 'CUSTOMER',
  CASHIER: 'CASHIER',
  PRODUCT: 'PRODUCT',
  BUDGET: 'BUDGET',
  BACKUP: 'BACKUP',
  STOCK: 'STOCK',
  BRAND: 'BRAND',
  USER: 'USER',
  SALE: 'SALE',
};

module.exports = entities;
