const budgetEventTypes = {
  IMPORT_BUDGET: 'IMPORT_BUDGET',
  CREATE_BUDGET: 'CREATE_BUDGET',
  READ_BUDGETS: 'READ_BUDGETS',
  UPDATE_BUDGET: 'UPDATE_BUDGET',
  DELETE_BUDGET: 'DELETE_BUDGET',
};

module.exports = budgetEventTypes;
