const cashierEventTypes = {
  IMPORT_CASHIERS: 'IMPORT_CASHIERS',
  CREATE_CASHIER: 'CREATE_CASHIER',
  READ_CASHIERS: 'READ_CASHIERS',
  UPDATE_CASHIER: 'UPDATE_CASHIER',
};

module.exports = cashierEventTypes;
