const customerEventTypes = {
  IMPORT_CUSTOMERS: 'IMPORT_CUSTOMERS',
  CREATE_CUSTOMER: 'CREATE_CUSTOMER',
  READ_CUSTOMERS: 'READ_CUSTOMERS',
  UPDATE_CUSTOMER: 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER: 'DELETE_CUSTOMER',
};

module.exports = customerEventTypes;
