const stockEventTypes = {
  UPDATE_PRODUCTS_IN_BATCH: 'UPDATE_PRODUCT_IN_BATCH',
  INSERT_PRODUCT_STOCK: 'INSERT_PRODUCT_STOCK',
  UPDATE_PRODUCT_STOCK: 'UPDATE_PRODUCT_STOCK',
  READ_STOCK: 'READ_STOCK',
};

module.exports = stockEventTypes;
