const stockEventTypes = {
  INSERT_PRODUCT_STOCK: 'INSERT_PRODUCT_STOCK',
  UPDATE_PRODUCT_STOCK: 'UPDATE_PRODUCT_STOCK',
  UPDATE_IN_BATCH: 'UPDATE_IN_BATCH',
  READ_STOCK: 'READ_STOCK',
};

module.exports = stockEventTypes;
