const entities = {
  OPERATION_REQUEST: 'OPERATION_REQUEST',
  OPERATION_RESPONSE: 'OPERATION_RESPONSE',
  USER: 'USER',
  BUDGET: 'BUDGET',
  PROVIDER: 'PROVIDER',
  CUSTOMER: 'CUSTOMER',
  STOCK: 'STOCK',
  BRAND: 'BRAND',
  PRODUCT: 'PRODUCT',
  SALE: 'SALE',
};

module.exports = entities;
