const entities = {
  OPERATION_RESPONSE: 'OPERATION_RESPONSE',
  OPERATION_REQUEST: 'OPERATION_REQUEST',
  PROVIDER: 'PROVIDER',
  CUSTOMER: 'CUSTOMER',
  CASHIER: 'CASHIER',
  PRODUCT: 'PRODUCT',
  BUDGET: 'BUDGET',
  BACKUP: 'BACKUP',
  STOCK: 'STOCK',
  BRAND: 'BRAND',
  USER: 'USER',
  SALE: 'SALE',
};

module.exports = entities;
