const providerEventTypes = {
  IMPORT_PROVIDERS: 'IMPORT_PROVIDERS',
  CREATE_PROVIDER: 'CREATE_PROVIDER',
  READ_PROVIDERS: 'READ_PROVIDERS',
  UPDATE_PROVIDER: 'UPDATE_PROVIDER',
  DELETE_PROVIDER: 'DELETE_PROVIDER',
};

module.exports = providerEventTypes;
